[package]
name = "learn_ogl_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.29.0"
glutin = "0.32.1"
glutin-winit = "0.5.0"
image = "0.25.2"
rand = "0.8.5"
softbuffer = "0.4.6"
winit = "0.30.5"

[build-dependencies]
gl_generator = "0.14.0"

